/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookmarks (offset pagination — deprecated)
         * @deprecated
         * @description Returns the caller's own bookmarks, newest first. With `visibility=public`
         *     returns public bookmarks from all users and works without authentication.
         *     Hidden bookmarks never appear in the public feed; owners see their own
         *     hidden bookmarks with `status: hidden`.
         *
         *     **Deprecated** in favor of the cursor-paginated `GET /api/v2/bookmarks`.
         *     Kept fully functional as the living example of deprecation signaling —
         *     every response carries `Deprecation`, `Sunset`, and a successor `Link`.
         */
        get: operations["listBookmarks"];
        put?: never;
        /** Create a bookmark */
        post: operations["createBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookmarks (cursor pagination)
         * @description Successor of `GET /api/v1/bookmarks`. Same semantics and filters, but
         *     keyset pagination: pass the `nextCursor` from the previous page to get the
         *     next one. Cursors are opaque — clients must never parse or construct them.
         *     Stable under concurrent inserts (no skipped or duplicated items between
         *     pages). `nextCursor` is absent on the last page.
         */
        get: operations["listBookmarksV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a bookmark
         * @description Owners can always read their bookmarks; others only when the bookmark is
         *     public. A private bookmark of another user yields `404`, not `403` —
         *     existence is not disclosed.
         */
        get: operations["getBookmark"];
        /** Replace a bookmark (owner only) */
        put: operations["updateBookmark"];
        post?: never;
        /** Delete a bookmark (owner only) */
        delete: operations["deleteBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/{id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a public bookmark
         * @description Any authenticated user may report a bookmark that is public and visible to
         *     them. At most one `open` report per user per bookmark (`409`); a new report
         *     is allowed once the previous one is resolved or withdrawn. Private or
         *     hidden bookmarks yield `404` — existence is not disclosed.
         */
        post: operations["reportBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own reports
         * @description Every report the caller has filed, newest first — the reporter's
         *     feedback loop. `status` shows what moderation decided; the resolution
         *     fields (`resolvedBy`, `resolvedAt`, `resolutionNote`) carry the
         *     disposition once a moderator acts.
         */
        get: operations["listMyReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the caller's own open report
         * @description The reporter may revise `reason` and `comment` while the report is
         *     `open`. Another user's report yields `404` — existence is not
         *     disclosed. A resolved report yields `409`.
         */
        put: operations["updateMyReport"];
        post?: never;
        /**
         * Withdraw the caller's own open report
         * @description Removes the report entirely; a withdrawn report no longer blocks filing
         *     a new one on the same bookmark. Another user's report yields `404` —
         *     existence is not disclosed. A resolved report yields `409`.
         */
        delete: operations["withdrawReport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Moderation queue (moderator) */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve or revise a report (moderator)
         * @description `dismissed` leaves the bookmark alone; `actioned` hides it and auto-resolves
         *     every other open report on the same bookmark as `actioned` with the same
         *     resolver and note. Decisions are revisable: any target status is accepted —
         *     `dismissed` ↔ `actioned` changes the disposition (`actioned` applies its
         *     side effects as usual), and `open` re-opens the report, clearing the
         *     resolution fields (any `note` sent with `open` is ignored). Moving away
         *     from `actioned` never restores the bookmark; use the bookmark status
         *     endpoint for that. Re-opening conflicts (`409`) when the reporter already
         *     has another open report on the same bookmark.
         */
        put: operations["resolveReport"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookmarks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Hide or restore a bookmark (moderator)
         * @description Restoring sets `status: active` and leaves `visibility` untouched.
         */
        put: operations["setBookmarkStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User directory (admin)
         * @description App-level accounts, lazily provisioned from JWTs — not Keycloak's user store.
         */
        get: operations["listUserAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One user account (admin) */
        get: operations["getUserAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{username}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Block or unblock a user (admin)
         * @description Blocking takes effect on the caller's next request — no session revocation.
         *     Admins cannot block themselves (`409`).
         */
        put: operations["setUserAccountStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse the audit trail (admin) */
        get: operations["listAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard stats (moderator) */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages (public, paginated) */
        get: operations["listMessages"];
        put?: never;
        /** Create a message (admin only) */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flat key→text bundle for one resolved language
         * @description Returns every message key with its text in the resolved language
         *     (`lang` parameter → `Accept-Language` → `en`); keys missing in that
         *     language fall back to their `en` text. `Content-Language` reports the
         *     language actually served. This is what frontends load on startup and
         *     on language switch.
         */
        get: operations["getMessageBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a message (public) */
        get: operations["getMessage"];
        /** Replace a message (admin only) */
        put: operations["updateMessage"];
        post?: never;
        /** Delete a message (admin only) */
        delete: operations["deleteMessage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's tags with usage counts, most used first */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity of the caller, as derived from the validated JWT */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — process is up */
        get: operations["livenessProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — dependencies (database) are reachable */
        get: operations["readinessProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Visibility: "private" | "public";
        Tag: string;
        /** @description Two-letter lowercase ISO 639-1 code. */
        LanguageCode: string;
        /** @description Dot-separated lowercase segments, e.g. `ui.nav.my-bookmarks`. */
        MessageKey: string;
        MessageInput: {
            key: components["schemas"]["MessageKey"];
            language: components["schemas"]["LanguageCode"];
            text: string;
            /** @description Context for translators. */
            description?: string;
        };
        Message: components["schemas"]["MessageInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        MessageBundle: {
            language: components["schemas"]["LanguageCode"];
            /** @description Flat key → localized text map. */
            messages: {
                [key: string]: string;
            };
        };
        BookmarkInput: {
            /**
             * Format: uri
             * @description Absolute http(s) URL.
             */
            url: string;
            title: string;
            notes?: string;
            /** @description Normalized server-side — trimmed, lowercased, deduplicated. */
            tags?: components["schemas"]["Tag"][];
            /** @default private */
            visibility?: components["schemas"]["Visibility"];
        };
        /**
         * @description Server-managed; changes only through moderation.
         * @enum {string}
         */
        BookmarkStatus: "active" | "hidden";
        Bookmark: components["schemas"]["BookmarkInput"] & {
            /** Format: uuid */
            id: string;
            /** @description Username of the creator. Immutable. */
            owner: string;
            status: components["schemas"]["BookmarkStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BookmarkCursorPage: {
            items: components["schemas"]["Bookmark"][];
            /** @description Opaque cursor for the next slice. Absent on the last page. */
            nextCursor?: string;
        };
        BookmarkStatusInput: {
            status: components["schemas"]["BookmarkStatus"];
            note?: string;
        };
        /** @enum {string} */
        ReportReason: "spam" | "offensive" | "broken-link" | "other";
        /** @enum {string} */
        ReportStatus: "open" | "dismissed" | "actioned";
        ReportInput: {
            reason: components["schemas"]["ReportReason"];
            comment?: string;
        };
        Report: components["schemas"]["ReportInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bookmarkId: string;
            reporter: string;
            status: components["schemas"]["ReportStatus"];
            /** Format: date-time */
            createdAt: string;
            resolvedBy?: string;
            /** Format: date-time */
            resolvedAt?: string;
            resolutionNote?: string;
        };
        ReportPage: {
            items: components["schemas"]["Report"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        ReportResolutionInput: {
            /** @enum {string} */
            resolution: "open" | "dismissed" | "actioned";
            note?: string;
        };
        /** @enum {string} */
        UserAccountStatus: "active" | "blocked";
        UserAccount: {
            username: string;
            /** Format: date-time */
            firstSeen: string;
            /** Format: date-time */
            lastSeen: string;
            status: components["schemas"]["UserAccountStatus"];
            /** @description Present while blocked. */
            blockedReason?: string;
            /** Format: int64 */
            bookmarkCount: number;
        };
        UserAccountPage: {
            items: components["schemas"]["UserAccount"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        UserStatusInput: {
            status: components["schemas"]["UserAccountStatus"];
            /** @description Required when blocking. */
            reason?: string;
        };
        AuditEntry: {
            /** Format: uuid */
            id: string;
            actor: string;
            /** @description Dot-separated verb, e.g. `report.resolved`, `user.blocked`. */
            action: string;
            targetType: string;
            targetId: string;
            /** @description Snapshot of the change. */
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        AdminStats: {
            totals: {
                /** Format: int64 */
                users: number;
                /** Format: int64 */
                bookmarks: number;
                /** Format: int64 */
                publicBookmarks: number;
                /** Format: int64 */
                hiddenBookmarks: number;
                /** Format: int64 */
                openReports: number;
            };
            /** @description Last 30 days including today, zero-filled, oldest first. */
            daily: {
                /** Format: date */
                date: string;
                bookmarksCreated: number;
                activeUsers: number;
            }[];
            /** @description Top tags by usage across all users. */
            topTags: components["schemas"]["TagCount"][];
        };
        BookmarkPage: {
            items: components["schemas"]["Bookmark"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        TagCount: {
            tag: components["schemas"]["Tag"];
            count: number;
        };
        User: {
            username: string;
            name?: string;
            /** Format: email */
            email?: string;
            /** @description Application roles from `realm_access.roles`, e.g. `["admin"]`. Empty for regular users. */
            roles: string[];
        };
        /** @description RFC 9457 problem details. `errors` carries field-level validation failures. */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            errors?: {
                field: string;
                messageKey: components["schemas"]["MessageKey"];
                /** @description Localized per the language resolution rules (`lang` → `Accept-Language` → `en`). */
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Validation failure. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid token (or, through the gateway, no session). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but missing the required role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource does not exist — or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The representation matches `If-None-Match`; the body is empty. */
        NotModified: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description A message with this `(key, language)` pair already exists. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Entity tag from a previous response; an unchanged representation returns `304`. */
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Entity tag of the current representation. */
        ETag: string;
        /** @description Always `no-cache`: responses may be stored but must be revalidated before reuse. */
        CacheControl: string;
        /** @description RFC 9745 — when the operation was deprecated, as `@` + Unix seconds. */
        Deprecation: string;
        /** @description RFC 8594 — HTTP-date after which the operation may be removed. */
        Sunset: string;
        /** @description RFC 8288 link to the replacing operation. */
        SuccessorLink: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBookmarks: {
        parameters: {
            query?: {
                /** @description Filter by tag. Repeatable; multiple values are combined with AND. */
                tag?: components["schemas"]["Tag"][];
                /** @description Case-insensitive substring match over title and notes. */
                q?: string;
                visibility?: components["schemas"]["Visibility"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of bookmarks. */
            200: {
                headers: {
                    Deprecation: components["headers"]["Deprecation"];
                    Sunset: components["headers"]["Sunset"];
                    Link: components["headers"]["SuccessorLink"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkInput"];
            };
        };
        responses: {
            /** @description Created. `Location` header points at the new resource. */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listBookmarksV2: {
        parameters: {
            query?: {
                /** @description Filter by tag. Repeatable; multiple values are combined with AND. */
                tag?: components["schemas"]["Tag"][];
                /** @description Case-insensitive substring match over title and notes. */
                q?: string;
                visibility?: components["schemas"]["Visibility"];
                /** @description Opaque cursor from the previous page's `nextCursor`. Omit for the first page. */
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A slice of bookmarks, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkCursorPage"];
                };
            };
            /** @description Validation failure — including a malformed or unresolvable cursor. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bookmark. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkInput"];
            };
        };
        responses: {
            /** @description The updated bookmark. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The bookmark is hidden by moderation and cannot be set to public. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reportBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportInput"];
            };
        };
        responses: {
            /** @description Report created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The caller already has an open report on this bookmark. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMyReports: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReportStatus"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the caller's reports, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportInput"];
            };
        };
        responses: {
            /** @description The updated report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The report is not open. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    withdrawReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The report is not open. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReportStatus"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of reports, oldest open first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    resolveReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportResolutionInput"];
            };
        };
        responses: {
            /** @description The resolved report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setBookmarkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkStatusInput"];
            };
        };
        responses: {
            /** @description The bookmark with its new status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUserAccounts: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on username. */
                q?: string;
                status?: components["schemas"]["UserAccountStatus"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of user accounts, most recently seen first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccountPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUserAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setUserAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusInput"];
            };
        };
        responses: {
            /** @description The account with its new status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccount"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Admins cannot block themselves. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listAuditEntries: {
        parameters: {
            query?: {
                actor?: string;
                /** @description Exact action, e.g. `report.resolved`. */
                action?: string;
                targetType?: string;
                targetId?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: {
                /** @description Entity tag from a previous response; an unchanged representation returns `304`. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals, a 30-day zero-filled daily series, and top tags. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Exact message key. */
                key?: components["schemas"]["MessageKey"];
                /** @description Case-insensitive substring match over key and text. */
                q?: string;
                language?: components["schemas"]["LanguageCode"];
                page?: number;
                size?: number;
            };
            header?: {
                /** @description Entity tag from a previous response; an unchanged representation returns `304`. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Created. `Location` header points at the new resource. */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getMessageBundle: {
        parameters: {
            query?: {
                /** @description Explicit language override; unsupported values fall back silently. */
                lang?: components["schemas"]["LanguageCode"];
            };
            header?: {
                /** @description Entity tag from a previous response; an unchanged representation returns `304`. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bundle. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    /** @description Language actually served. */
                    "Content-Language"?: components["schemas"]["LanguageCode"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageBundle"];
                };
            };
            304: components["responses"]["NotModified"];
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Entity tag from a previous response; an unchanged representation returns `304`. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description The updated message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tags: components["schemas"]["TagCount"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    livenessProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readinessProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
