play.http.secret.key = "stackverse-play-scala-local-development-only"
play.server.pidfile.path = "/dev/null"
play.server.http.port = 8080
play.server.http.port = ${?PORT}
play.modules.enabled += "stackverse.Module"
play.filters.enabled = []
