play.http.secret.key = "stackverse-play-scala-local-development-only"
play.http.secret.key = ${?APPLICATION_SECRET}
play.server.pidfile.path = "/dev/null"
play.server.http.port = 8080
play.server.http.port = ${?PORT}
play.modules.enabled += "modules.StackverseModule"
play.filters.enabled = []

database-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    # Keep in sync with Db.scala Hikari maximumPoolSize.
    fixed-pool-size = 10
  }
}
