source "https://rubygems.org"

ruby "3.4.6"

gem "bootsnap", "~> 1.18", require: false
gem "jwt", "~> 3.2"
gem "pg", "~> 1.6"
gem "puma", "~> 8.0"
gem "rails", "~> 8.1.3"

group :test do
  gem "minitest", "~> 6.0"
  gem "simplecov", "~> 0.22", require: false
end
