source "https://rubygems.org"

ruby "3.4.6"

gem "bootsnap", "~> 1.18", require: false
gem "jwt", "~> 2.10"
gem "pg", "~> 1.6"
gem "puma", "~> 6.6"
gem "rails", "~> 7.2.2"

group :test do
  gem "minitest", "~> 5.25"
  gem "simplecov", "~> 0.22", require: false
end
